services:
  server:
    build:
      context: ./server
    container_name: myapp-server
    env_file:
      - ./server/.env
    ports:
      - "5001:5001"

  client:
    build:
      context: ./client
    container_name: myapp-client
    depends_on:
      - server
    ports:
      - "8001:80"